tasks:
  - before: |
      rm -rf $HOME/.cargo
      unset CARGO_HOME
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source $HOME/.cargo/env
      echo 'export CARGO_HOME="$HOME/.cargo"' >> ~/.bashrc
      source ~/.bashrc
      sudo wget -c https://github.com/WebAssembly/binaryen/releases/download/version_105/binaryen-version_105-x86_64-linux.tar.gz -O - | sudo tar -xz -C /tmp/
      sudo cp /tmp/binaryen-version_105/bin/wasm-opt /usr/bin/
    init: |
      gp open README.md
      clear && printf '\e[3J' && history -c

vscode:
  extensions:
    - matklad.rust-analyzer
